import app, { ModuleRegistry } from "./app";
import { configService, db, Logger, findAvailablePort } from "./core";

const startServer = async () => {
  try {
    // 1. Connect to the database
    await db.connect();

    // 2. Initialize modules
    await ModuleRegistry.initialize();

    // Resolve an available port starting from the configured port
    const basePort = configService.app.port;
    const resolvedPort = await findAvailablePort(basePort);

    // 3. Start Express app listening
    const server = app.listen(resolvedPort, () => {
      Logger.info(`🚀 Vera Platform server running on http://localhost:${resolvedPort} [${configService.app.env}]`);

      // Print dynamic secrets banner if any were auto-generated
      if (configService.isJwtSecretAutoGenerated || configService.isOAuthKeyAutoGenerated) {
        console.log("\n============================================================");
        console.log("🔑 VERA SECURITY PLATFORM - AUTO-GENERATED ACCESS CREDENTIALS");
        console.log("============================================================");
        console.log("The following secrets were automatically generated on startup:\n");
        if (configService.isJwtSecretAutoGenerated) {
          console.log(`  JWT_SECRET:                 ${configService.security.jwtSecret}`);
        }
        if (configService.isOAuthKeyAutoGenerated) {
          console.log(`  OAUTH_TOKEN_ENCRYPTION_KEY: ${configService.security.oauthTokenEncryptionKey}`);
        }
        console.log("\nPlease save/keep these secrets if you need to use or access the platform!");
        console.log("============================================================\n");
      }
    });

    // Graceful shutdown handling
    const gracefulShutdown = async (signal: string) => {
      Logger.info(`Received ${signal}. Starting graceful shutdown...`);

      server.close(async () => {
        Logger.info("HTTP server closed.");
        try {
          await db.disconnect();
          Logger.info("Graceful shutdown completed successfully.");
          process.exit(0);
        } catch (err) {
          Logger.error("Error during database disconnection:", err);
          process.exit(1);
        }
      });

      // Force close after 10 seconds
      setTimeout(() => {
        Logger.error("Could not close connections in time, forcefully shutting down");
        process.exit(1);
      }, 10000);
    };

    process.on("SIGTERM", () => gracefulShutdown("SIGTERM"));
    process.on("SIGINT", () => gracefulShutdown("SIGINT"));

  } catch (error) {
    Logger.error("Fatal startup error, exiting process...", error);
    process.exit(1);
  }
};

startServer();
